version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scraper
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./scraper-backend
      dockerfile:  Dockerfile
    container_name: scraper-backend
    environment:
      DATABASE_URL: mysql://root:root@db:3306/scraper
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./media-viewer/
      dockerfile: Dockerfile
    container_name: media-viewer
    ports:
      - "3001:3001"
    depends_on:
      - backend


volumes:
  db_data:

